CREATE TABLE roleplay_sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    persona_id UUID,
    persona_name VARCHAR(100),
    company VARCHAR(100),
    target_role VARCHAR(100),
    interview_type VARCHAR(50),
    conversation_history JSONB DEFAULT '[]',
    overall_score DECIMAL(5,2),
    communication_score DECIMAL(5,2),
    technical_depth_score DECIMAL(5,2),
    confidence_score DECIMAL(5,2),
    strengths JSONB DEFAULT '[]',
    improvements JSONB DEFAULT '[]',
    action_plan TEXT,
    filler_word_count INTEGER DEFAULT 0,
    round_label VARCHAR(100),
    is_completed BOOLEAN DEFAULT FALSE,
    time_spent_seconds INTEGER DEFAULT 0,
    started_at TIMESTAMP DEFAULT NOW(),
    completed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW()
);
