server.port=8081

spring.datasource.url=jdbc:postgresql://postgres:5432/interview_prep_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=20

spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASSWORD}

spring.jpa.show-sql=false
logging.level.com.interviewprep=INFO
